# Generated by Django 5.0.1 on 2024-02-17 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('header', models.CharField(blank=True, help_text='Optinal', max_length=250, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('content', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('application_area', models.TextField()),
                ('suitable_production_process', models.TextField()),
                ('characteristics', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Products Categories',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, help_text='Optinal', max_length=250, null=True)),
                ('content', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.article')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=255)),
                ('image_one', models.ImageField(upload_to='', verbose_name='First Image')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Second Image')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Third Image')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('published_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-published_on',),
            },
        ),
    ]
